application = "quitz001"
favicon = "./resources/favicon.ico"

[db]
    [db.mysql]
        connection = "sql6443261:KuSYXAhx5j@tcp(sql6.freemysqlhosting.net:3306)/sql6443261?charset=utf8&parseTime=True&loc=Local"

[status]
    APP-200 = "Success."
    APP-500 = "Internal server error."
    APP-400-001 = "พบการกรอกข้อมูลไม่ถูกต้อง"
    APP-400-002 = "วันที่เริ่มต้นต้องน้อยกว่าหรือเท่ากับวันที่สิ้นสุด"
    APP-400-003 = "วันที่เริ่มต้นต้องมากกว่าวันปัจจุบัน"
    APP-400-004 = "มีการทำนัดหมายในช่วงเวลาดังกล่าว กรุณาเลือกช่วงเวลานัดหมายใหม่อีกครั้ง"
    APP-400-005 = "มีการทำนัดหมายนอกช่วงเวลา กรุณาเลือกช่วงเวลานัดหมายใหม่อีกครั้ง"
    APP-404-001 = "ไม่พบข้อมูลผู้ใช่้งาน"
    APP-404-002 = "ไม่พบข้อมูลแพทย์"
    APP-404-003 = "ไม่พบข้อมูลตารางการตรวจ"
    APP-404-004 = "ไม่พบข้อมูลการนัดหมาย"
    